'use client';
import {useRef,useState} from 'react';import {useRouter} from 'next/navigation';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {fileMime,MAX_FILE_BYTES} from '@/lib/files/schema';import type {ProjectFile,FileEvent} from '@/lib/files/data';
export function ProjectFiles({id,files,history=[],staff=false,userId}:{id:string;files:ProjectFile[];history?:FileEvent[];staff?:boolean;userId:string}){
 const router=useRouter();const input=useRef<HTMLInputElement>(null);const [selected,setSelected]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [reasons,setReasons]=useState<Record<string,string>>({});
 const base=`/api/${staff?'admin':'client'}/projects/${id}/files`;
 async function post(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const result=await response.json();if(response.status===401){router.replace(staff?'/admin/login':'/client/login');router.refresh();}if(!response.ok)throw new Error(result.error||'The file action failed.');return result;}
 async function upload(){
  if(!selected)return;const mime=fileMime(selected.name);if(!mime||selected.size<1||selected.size>MAX_FILE_BYTES){setMessage('Choose a PDF, PNG, JPG, WebP, ZIP or TXT file up to 10 MB.');return;}
  setBusy(true);setMessage('Preparing upload…');
  try{const reservation=await post(base,{action:'reserve',id:crypto.randomUUID(),filename:selected.name,size:selected.size,mime});setMessage('Uploading file…');const response=await fetch(reservation.signedUrl,{method:'PUT',headers:{'Content-Type':mime,'Cache-Control':'max-age=0'},body:await selected.arrayBuffer(),signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error('Upload failed. Reload to review the pending file before trying another upload.');setMessage('Verifying file…');await post(base,{action:'finalize',id:reservation.id});setSelected(null);if(input.current)input.current.value='';setMessage('File received.');}
  catch(e){setMessage(e instanceof Error&&e.name!=='TimeoutError'?e.message:'The result could not be confirmed. Reload to review pending files.');}finally{setBusy(false);router.refresh();}
 }
 async function action(file:ProjectFile,action:'finalize'|'share'|'private'|'withdraw'){
  setBusy(true);setMessage('');try{await post(base,{action,id:file.id,...(action==='finalize'?{}:{expectedRevision:file.revision}),...(action==='withdraw'?{reason:reasons[file.id]||''}:{})});setMessage(action==='finalize'?'File verified.':action==='share'?'File shared with assigned clients.':action==='private'?'File sharing removed.':'File withdrawn.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'The result could not be confirmed.');router.refresh();}finally{setBusy(false);}
 }
 async function download(file:ProjectFile){setBusy(true);setMessage('');try{const data=await post(`${base}/${file.id}/download`,{});window.location.assign(data.url);}catch(e){setMessage(e instanceof Error?e.message:'Download failed.');}finally{setBusy(false);}}
 return <div className="mt-8 space-y-6"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Project files</h2><p className="mt-3 text-sm text-muted-foreground">{staff?'Uploads start private. Share a verified file when it is ready for the client.':'Send project inputs to Bivi and download files shared with your project. Your uploads are visible to you and Bivi until staff share them.'}</p><fieldset disabled={busy} className="mt-5 space-y-3"><legend className="sr-only">Upload a project file</legend><label htmlFor="project-file" className="block text-sm font-medium">Choose file</label><Input ref={input} id="project-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.zip,.txt" onChange={e=>setSelected(e.target.files?.[0]??null)} className="h-auto min-h-11 py-2"/><p className="text-xs text-muted-foreground">PDF, PNG, JPG, WebP, ZIP or TXT · up to 10 MB per file</p><Button type="button" disabled={!selected} onClick={upload}>Upload file</Button></fieldset>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}</section>
 <section className="space-y-4" aria-label="Project file list">{!files.length&&<p className="text-sm text-muted-foreground">No project files yet.</p>}{files.map(file=><article key={file.id} className="rounded-2xl border border-border bg-card p-5"><h3 className="break-all font-medium">{file.filename}</h3><p className="mt-2 text-xs text-muted-foreground">{(file.size_bytes/1024).toFixed(1)} KB · {new Date(file.created_at).toISOString().slice(0,10)} · {file.state==='withdrawn'?'Withdrawn':file.state==='pending'?'Awaiting verification':file.shared?'Shared with assigned clients':file.uploader_id===userId?'Your upload':'Private to Bivi'}</p><div className="mt-4 flex flex-wrap gap-3">{file.state==='ready'&&<Button type="button" variant="outline" disabled={busy} onClick={()=>download(file)} aria-label={`Download ${file.filename}`}>Download</Button>}{file.state==='pending'&&file.uploader_id===userId&&<Button type="button" variant="outline" disabled={busy||new Date(file.expires_at).getTime()<=Date.now()} onClick={()=>action(file,'finalize')} aria-label={`Finish upload ${file.filename}`}>Finish verification</Button>}{staff&&file.state==='ready'&&<Button type="button" variant="outline" disabled={busy} onClick={()=>action(file,file.shared?'private':'share')} aria-label={`${file.shared?'Make private':'Share'} ${file.filename}`}>{file.shared?'Make private':'Share with clients'}</Button>}</div>{file.state==='pending'&&<p className="mt-3 text-xs text-muted-foreground">Finish verification after a successful upload. Reservations expire after two hours; ask Bivi to review failed or expired uploads.</p>}{staff&&file.state!=='withdrawn'&&<details className="mt-4"><summary className="cursor-pointer text-sm">Withdraw file</summary><div className="mt-3 space-y-3"><label htmlFor={`withdraw-${file.id}`} className="block text-sm">Reason for withdrawing {file.filename}</label><Textarea id={`withdraw-${file.id}`} maxLength={2000} value={reasons[file.id]||''} onChange={e=>setReasons({...reasons,[file.id]:e.target.value})} disabled={busy}/><p className="text-xs text-muted-foreground">Withdrawal removes access and keeps the file history. Upload a new file to replace it.</p><Button type="button" variant="outline" disabled={busy||!reasons[file.id]?.trim()} onClick={()=>action(file,'withdraw')} aria-label={`Withdraw ${file.filename}`}>Withdraw file</Button></div></details>}</article>)}</section>
 {staff&&history.length>0&&<section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">File history</h2><p className="mt-2 text-xs text-muted-foreground">Most recent 50 actions</p><ol className="mt-4 space-y-3">{history.map(event=><li key={event.id} className="border-t border-border pt-3 text-sm"><p className="break-words">{files.find(f=>f.id===event.file_id)?.filename||'File'} · {event.action} · revision {event.revision}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.created_at).toISOString()}</p>{event.reason&&<p className="mt-2 whitespace-pre-wrap break-words">{event.reason}</p>}</li>)}</ol></section>}</div>;
}
