import Link from 'next/link';import {notFound} from 'next/navigation';import {z} from 'zod';import {requireStaff} from '@/lib/admin/auth';import {getProject} from '@/lib/projects/data';import {projectComments,projectActivity} from '@/lib/discussion/data';import {ProjectDiscussion} from '@/components/admin/ProjectDiscussion';
const pageNumber=(s:unknown)=>typeof s==='string'&&/^\d+$/.test(s)&&Number(s)>=1&&Number(s)<=10000?Number(s):1;
export default async function DiscussionPage({params,searchParams}:{params:{id:string};searchParams:{page?:string;activity?:string;task?:string}}){
 const {client,user}=await requireStaff();if(!z.string().uuid().safeParse(params.id).success)notFound();const {record}=await getProject(client,params.id);if(!record)notFound();const task=typeof searchParams.task==='string'&&searchParams.task.length>0&&searchParams.task.length<=100?searchParams.task:null;const page=pageNumber(searchParams.page),activityPage=pageNumber(searchParams.activity);
 const [discussion,activity]=await Promise.all([projectComments(client,params.id,page,task),projectActivity(client,params.id,activityPage)]);
 function href(p:number,a:number,t:string|null){const query=new URLSearchParams({page:String(p),activity:String(a),...(t?{task:t}:{})});return `/admin/projects/${params.id}/discussion?${query}`;}
 const pages=Math.max(1,Math.ceil(discussion.total/25)),activityPages=Math.max(1,Math.ceil(activity.total/25));
 return <><Link href={`/admin/projects/${params.id}`} className="text-sm underline underline-offset-4">Back to project</Link><h1 className="mt-6 break-words font-heading text-3xl font-semibold">{record.body.title} · Discussion and activity</h1><nav aria-label="Filter discussion by task" className="mt-6 flex flex-wrap gap-3 text-sm"><Link href={href(1,activityPage,null)} aria-current={!task?'page':undefined} className="rounded-xl border border-border px-3 py-2">All comments</Link>{record.body.tasks.map(t=><Link key={t.id} href={href(1,activityPage,t.id)} aria-current={task===t.id?'page':undefined} className="max-w-full break-words rounded-xl border border-border px-3 py-2">{t.title}</Link>)}</nav><ProjectDiscussion id={params.id} revision={record.revision} tasks={record.body.tasks} comments={discussion.comments} userId={user.id} filteredTask={task}/><nav aria-label="Discussion pages" className="mt-5 flex flex-wrap gap-5 text-sm"><p>Comments page {page} of {pages} · {discussion.total} records</p>{page>1&&<Link href={href(page-1,activityPage,task)} className="underline">Previous comments</Link>}{page<pages&&<Link href={href(page+1,activityPage,task)} className="underline">Next comments</Link>}</nav>
 <section className="mt-10 rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Project activity</h2><p className="mt-3 text-sm text-muted-foreground">Internal timeline for this inquiry and project. Times shown in UTC.</p><ol className="mt-5 space-y-4">{activity.events.map(event=><li key={event.event_id} className="border-t border-border pt-4"><p className="text-sm font-medium capitalize">{event.source} · {event.action.replaceAll('_',' ')}</p>{event.detail&&<p className="mt-2 whitespace-pre-wrap break-words text-sm">{event.detail}</p>}<p className="mt-2 text-xs text-muted-foreground">{new Date(event.created_at).toISOString()}</p></li>)}</ol>{!activity.events.length&&<p className="mt-5 text-sm text-muted-foreground">No activity yet.</p>}<nav aria-label="Activity pages" className="mt-6 flex flex-wrap gap-5 text-sm"><p>Activity page {activityPage} of {activityPages}</p>{activityPage>1&&<Link href={href(page,activityPage-1,task)} className="underline">Previous activity</Link>}{activityPage<activityPages&&<Link href={href(page,activityPage+1,task)} className="underline">Next activity</Link>}</nav></section></>;
}
