import { Download, FileDown, FilePlus2, ShieldCheck, Upload } from 'lucide-react';
import { monthlyLabor, reportCards, taxItems } from '../mockData';
import { Card, SectionTitle, StatusPill } from '../ui';

export function TaxView() {
  return <div className="space-y-6"><Card className="p-5 md:p-6"><SectionTitle eyebrow="Compliance calendar" title="Tax obligations" /><div className="space-y-3">{taxItems.map((item) => <div key={item.name} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/[0.025] p-4"><div><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#7db7ff]"/><p className="text-sm font-medium text-white">{item.name}</p></div><p className="mt-1 text-xs text-white/35">Due {item.due}</p></div><div className="flex items-center gap-4"><p className="text-sm text-white/60">{item.amount}</p><StatusPill tone={item.status === 'Upcoming' ? 'yellow' : 'green'}>{item.status}</StatusPill></div></div>)}</div></Card><Card className="p-5 md:p-6"><SectionTitle eyebrow="Filing health" title="Compliance status" /><div className="grid gap-3 md:grid-cols-3"><Compliance label="Federal setup" detail="Active and verified"/><Compliance label="State registrations" detail="Texas · Active"/><Compliance label="Year-end forms" detail="48 W-2 profiles ready"/></div></Card></div>;
}

function Compliance({ label, detail }: { label: string; detail: string }) { return <div className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-5 h-2 w-2 rounded-full bg-[#a9f04d]"/><p className="text-sm font-medium text-white">{label}</p><p className="mt-1 text-xs text-white/35">{detail}</p></div> }

export function DocumentsView({ documents, onImport, onExport }: { documents: { name: string; type: string; updated: string; size: string }[]; onImport: (file: File) => void; onExport: () => void }) {
  return <Card className="p-5 md:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><SectionTitle eyebrow="File center" title="Company documents"/><div className="flex gap-2"><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-medium text-white/60 hover:bg-white/[0.04]"><Upload size={14}/>Import<input type="file" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) onImport(file); event.currentTarget.value = ''; }}/></label><button onClick={onExport} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-semibold text-[#071426]"><Download size={14}/>Export index</button></div></div><div className="space-y-2">{documents.map((document) => <div key={document.name} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#173b63] text-[#9cc8ff]"><FilePlus2 size={16}/></span><div><p className="text-sm font-medium text-white">{document.name}</p><p className="mt-1 text-xs text-white/35">{document.type} · {document.size}</p></div></div><p className="text-xs text-white/35">Updated {document.updated}</p></div>)}</div></Card>;
}

export function ReportsView({ onExport }: { onExport: () => void }) {
  const max = Math.max(...monthlyLabor);
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{reportCards.map((card) => <Card key={card.label} className="p-5"><p className="text-xs text-white/35">{card.label}</p><div className="mt-2 flex items-end justify-between"><p className="text-2xl font-semibold text-white">{card.value}</p><StatusPill tone={card.tone as 'green'|'yellow'|'red'}>{card.change}</StatusPill></div></Card>)}</div><Card className="p-5 md:p-6"><SectionTitle eyebrow="Last 12 months" title="Labor cost trend" action={<button onClick={onExport} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-medium text-white/60"><FileDown size={14}/>Export CSV</button>}/><div className="mt-6 flex h-64 items-end gap-2 border-b border-white/10 pb-4">{monthlyLabor.map((value, index) => <div key={index} className="flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-[#7db7ff]/65 transition hover:bg-[#a9f04d]" style={{ height: `${Math.max(18, (value/max)*100)}%` }} title={`$${value}k`}/></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-white/25"><span>Sep</span><span>Dec</span><span>Mar</span><span>Jun</span><span>Aug</span></div></Card></div>;
}
