import 'server-only';import {cookies} from 'next/headers';import {createClient} from '@supabase/supabase-js';import {createHmac} from 'node:crypto';import {z} from 'zod';import {sealSession,openSession} from './session-crypto.mjs';
export const SETUP_COOKIE='bivi_password_setup';
export function accessOrigin(){const url=new URL(process.env.INQUIRY_APP_URL||'');if(url.username||url.password||url.search||url.hash||url.pathname!=='/'||(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname))))throw new Error('Configure the canonical HTTPS application origin.');return url.origin;}
export function privilegedClient(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Access setup is unavailable.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:(input,init)=>fetch(input,{...init,cache:'no-store',signal:init?.signal||AbortSignal.timeout(15000)})}});}
export async function reserveAuth(kind:'recovery'|'invite',email:string){const bucket=createHmac('sha256',process.env.SUPABASE_SERVICE_ROLE_KEY!).update(email.toLowerCase()).digest('hex');const {data,error}=await privilegedClient().rpc('reserve_portal_auth_action',{p_kind:kind,p_bucket:bucket});if(error)throw new Error('Auth request limits are unavailable.');return data===true;}
const session=z.object({accessToken:z.string().min(1),refreshToken:z.string().min(1),userId:z.string().uuid(),expiresAt:z.number()});
export function setupSession(){const result=session.safeParse(openSession(cookies().get(SETUP_COOKIE)?.value,process.env.SUPABASE_SERVICE_ROLE_KEY));return result.success?result.data:null;}
export function encodeSetup(data:{accessToken:string;refreshToken:string;userId:string;expiresAt:number}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('Access setup is unavailable.');session.parse(data);const value=sealSession(data,key);if(value.length>3800)throw new Error('Setup session is too large.');return value;}
export const setupCookieOptions={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/api/client/password',maxAge:600};
