import 'server-only';
import {z} from 'zod';import type {SupabaseClient} from '@supabase/supabase-js';import {projectBodySchema} from './schema';import {proposalBodySchema} from '@/lib/proposals/schema';import {checklistBodySchema} from '@/lib/onboarding/checklist-schema';import {readinessBodySchema} from '@/lib/onboarding/schema';
const summary=z.object({request_id:z.string().uuid(),state:z.enum(['active','on_hold','completed']),body:projectBodySchema,updated_at:z.string()});
const record=summary.extend({proposal_version:z.number().int(),revision:z.number().int(),scope_snapshot:proposalBodySchema,onboarding_snapshot:checklistBodySchema,onboarding_items_snapshot:z.array(z.record(z.unknown())).catch([]),readiness_snapshot:readinessBodySchema,activated_readiness_revision:z.number(),activated_onboarding_revision:z.number(),activated_at:z.string(),activated_by:z.string().nullable()});
export type ProjectRecord=z.infer<typeof record>;
const event=z.object({id:z.number(),action:z.string(),reason:z.string(),actor:z.string().nullable(),created_at:z.string(),snapshot:z.object({state:z.enum(['active','on_hold','completed']),revision:z.number(),body:projectBodySchema})});
export type ProjectEvent=z.infer<typeof event>;
export async function listProjects(client:SupabaseClient,state:string|null,page:number){let query=client.from('inquiry_projects').select('request_id,state,body,updated_at',{count:'exact'}).order('updated_at',{ascending:false}).order('request_id',{ascending:false}).range((page-1)*25,page*25-1);if(state)query=query.eq('state',state);const {data,error,count}=await query;if(error)throw new Error('Projects could not be loaded. Check the sixth migration.');return {projects:z.array(summary).parse(data??[]),total:count??0};}
export async function getProject(client:SupabaseClient,id:string){const {data,error}=await client.from('inquiry_projects').select('*').eq('request_id',id).maybeSingle();if(error)throw new Error('Project could not be loaded. Check migrations 006 and 011.');const h=await client.from('inquiry_project_history').select('*').eq('request_id',id).order('id',{ascending:false}).limit(50);if(h.error)throw new Error('Project history could not be loaded.');return {record:data?record.parse(data):null,history:z.array(event).parse(h.data??[])};}
