import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
const migrations=new URL('../../supabase/migrations/',import.meta.url);

import assert from 'node:assert/strict';
test('Bivi migrations 001–009: intake, workflow gates, client isolation and private files',async()=>{
const db=new PGlite();
try {
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to authenticated;`);
for(const f of ['202610060001_project_inquiries.sql','202610060002_inquiry_staff_and_reviews.sql']) await db.exec(fs.readFileSync(new URL(f,migrations),'utf8'));
// Intake RPC remains service-role only; retry and rate-limit behavior is shared across instances.
const submit=async(requestId,hash='a'.repeat(64),bucket='b'.repeat(64))=>(await db.query('select submit_project_inquiry($1,$2,$3,$4) r',[requestId,{email:'test@example.invalid'},hash,bucket])).rows[0].r;
await db.exec('set role anon;');await assert.rejects(submit(randomUUID()),/permission denied/);
await db.exec('reset role;set role authenticated;');await assert.rejects(submit(randomUUID()),/permission denied/);
await db.exec('reset role;set role service_role;');const intakeId=randomUUID();assert.equal(await submit(intakeId),'created');assert.equal(await submit(intakeId),'duplicate');assert.equal(await submit(intakeId,'c'.repeat(64)),'conflict');
for(let i=0;i<4;i++)assert.equal(await submit(randomUUID()),'created');assert.equal(await submit(randomUUID()),'rate_limited');
await db.exec("reset role;update inquiry_rate_limits set request_count=200 where bucket='global';set role service_role;");assert.equal(await submit(randomUUID(),'a'.repeat(64),'d'.repeat(64)),'rate_limited');
await db.exec('reset role;delete from project_inquiries;delete from inquiry_rate_limits;');
console.log('PASS: private inquiry intake, idempotent retries, conflicting references and email/global rate limits');
const staff='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${staff}'),('${other}'); insert into inquiry_staff(user_id) values('${staff}'); insert into project_inquiries(request_id,payload,payload_hash) values('${id}','{}',repeat('a',64)); set role authenticated; select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query('select * from project_inquiries')).rows.length,0);
await assert.rejects(db.query(`select review_project_inquiry('${id}',0,'qualified','x')`),/Staff authorization/);
await assert.rejects(db.query(`update project_inquiries set status='qualified'`),/permission denied/);
await assert.rejects(db.query('select * from inquiry_staff'),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
assert.equal((await db.query('select * from project_inquiries')).rows.length,1);
const review=async(rev,status,note)=>(await db.query('select review_project_inquiry($1,$2,$3,$4) as r',[id,rev,status,note])).rows[0].r;
assert.equal((await review(0,'qualified','Fits scope')).result,'updated');
assert.equal((await review(0,'declined','stale')).result,'conflict');
assert.equal((await review(1,'qualified','Fits scope')).result,'unchanged');
assert.equal((await db.query('select * from inquiry_review_history')).rows.length,1);
const row=(await db.query('select * from project_inquiries')).rows[0];assert.equal(row.revision,1);assert.equal(row.reviewed_by,staff);
await db.exec(`reset role; update inquiry_staff set active=false; set role authenticated;`);
assert.equal((await db.query('select * from project_inquiries')).rows.length,0);
await assert.rejects(review(1,'declined','Revoked'),/Staff authorization/);
await db.exec('reset role; set role anon;');await assert.rejects(db.query('select * from project_inquiries'),/permission denied/);
console.log('PASS: migrations, staff RLS, nonstaff/anonymous denial, direct-write denial, atomic history, stale revision, idempotent review, revoked staff');
await db.exec("reset role; update inquiry_staff set active=true; update project_inquiries set status='qualified';");
await db.exec(fs.readFileSync(new URL('202610060003_inquiry_proposals.sql',migrations),'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${other}',false)`);
await assert.rejects(db.query('select manage_inquiry_proposal($1,$2)',[id,{action:'create',expectedVersion:0,body:{}}]),/Staff authorization/);
assert.equal((await db.query('select * from inquiry_proposals')).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
const body={title:'Proposal',summary:'Goals',items:[{serviceId:'logo-design',name:'Logo',quantity:2,blueprintVersion:1}],deliverables:'Files',exclusions:'None',clientInputs:'Brief',revisions:'2 rounds',schedule:'2 weeks after inputs',fees:'USD 500; 50% deposit'};
const cmd=async c=>(await db.query('select manage_inquiry_proposal($1,$2) as r',[id,c])).rows[0].r;
await assert.rejects(cmd({action:'create',expectedVersion:0,body:{...body,items:[{...body.items[0],quantity:-1}]}}),/Invalid scope/);
assert.equal((await cmd({action:'create',expectedVersion:0,body})).version,1);
assert.equal((await cmd({action:'create',expectedVersion:0,body})).result,'conflict');
await assert.rejects(db.query("update inquiry_proposals set status='accepted'"),/permission denied/);
assert.equal((await cmd({action:'save',version:1,expectedRevision:0,body:{...body,fees:''}})).result,'saved');
await assert.rejects(cmd({action:'issue',version:1,expectedRevision:1}),/Complete proposal terms/);
assert.equal((await cmd({action:'save',version:1,expectedRevision:1,body})).result,'saved');
assert.equal((await cmd({action:'issue',version:1,expectedRevision:2})).result,'saved');
assert.equal((await cmd({action:'save',version:1,expectedRevision:3,body:{...body,title:'Tampered'}})).result,'locked');
assert.equal((await cmd({action:'create',expectedVersion:1,body:{...body,title:'Second'}})).version,2);
assert.equal((await cmd({action:'accept',version:1,expectedRevision:3,approver:'Client',acceptedOn:'2026-10-01',evidence:'Email'})).result,'locked');
assert.equal((await cmd({action:'issue',version:2,expectedRevision:0})).result,'saved');
assert.equal((await db.query('select status from inquiry_proposals where version=1')).rows[0].status,'superseded');
await assert.rejects(cmd({action:'accept',version:2,expectedRevision:1,approver:'',acceptedOn:'2026-10-01',evidence:'Email'}),/Acceptance details/);
await assert.rejects(cmd({action:'accept',version:2,expectedRevision:1,approver:'Client',acceptedOn:'2026-02-30',evidence:'Email'}),/Invalid acceptance date/);
assert.equal((await cmd({action:'accept',version:2,expectedRevision:1,approver:'Client',acceptedOn:'2026-10-01',evidence:'Approval email ref'})).result,'saved');
assert.equal((await cmd({action:'create',expectedVersion:2,body})).result,'locked');
assert.equal((await cmd({action:'save',version:2,expectedRevision:2,body})).result,'locked');
assert.equal((await cmd({action:'accept',version:2,expectedRevision:1,approver:'Client',acceptedOn:'2026-10-01',evidence:'Email'})).result,'conflict');
const accepted=(await db.query('select * from inquiry_proposals where version=2')).rows[0];assert.equal(accepted.recorded_by,staff);assert.equal(accepted.body.title,'Second');assert.equal(accepted.acceptance_evidence,'Approval email ref');
await db.exec('reset role; update inquiry_staff set active=false; set role authenticated;');
assert.equal((await db.query('select * from inquiry_proposals')).rows.length,0);
await assert.rejects(cmd({action:'create',expectedVersion:2,body}),/Staff authorization/);
console.log('PASS: proposal validation, draft edits, required issue terms, immutable issued/accepted scope, superseding versions, concurrent/retry conflicts, acceptance evidence and date, staff-only RLS/RPC');
await db.exec('reset role; update inquiry_staff set active=true;');
await db.exec(fs.readFileSync(new URL('202610060004_onboarding_readiness.sql',migrations),'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${other}',false)`);
const gate=async c=>(await db.query('select manage_inquiry_readiness($1,$2) as r',[id,c])).rows[0].r;
const pending={agreementStatus:'pending',agreementRef:'',signatory:'',signedOn:null,depositStatus:'pending',depositAmount:'',currency:'',depositRef:'',depositOn:null,waiverReason:'',notes:''};
await assert.rejects(gate({action:'save',expectedRevision:0,body:pending}),/Staff authorization/);
assert.equal((await db.query('select * from inquiry_readiness')).rows.length,0);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
assert.equal((await gate({action:'save',expectedRevision:0,body:pending})).revision,1);
assert.equal((await gate({action:'save',expectedRevision:0,body:pending})).result,'conflict');
assert.equal((await gate({action:'release',expectedRevision:1})).result,'incomplete');
await assert.rejects(db.query("update inquiry_readiness set state='ready'"),/permission denied/);
await assert.rejects(gate({action:'save',expectedRevision:1,body:{...pending,agreementStatus:'signed'}}),/Invalid readiness/);
const complete={...pending,agreementStatus:'signed',agreementRef:'AGREEMENT-001',signatory:'Client',signedOn:'2026-10-01',depositStatus:'received',depositAmount:'250.00',currency:'USD',depositRef:'RECEIPT-001',depositOn:'2026-10-02'};
await assert.rejects(gate({action:'save',expectedRevision:1,body:{...complete,depositOn:'2026-02-30'}}),/Invalid readiness/);
await assert.rejects(gate({action:'save',expectedRevision:1,body:{...complete,depositAmount:'0'}}),/Invalid readiness/);
await assert.rejects(gate({action:'save',expectedRevision:1,body:{...complete,signedOn:'2999-01-01'}}),/Invalid readiness/);
assert.equal((await gate({action:'save',expectedRevision:1,body:complete})).revision,2);
assert.equal((await gate({action:'release',expectedRevision:1})).result,'conflict');
assert.equal((await gate({action:'release',expectedRevision:2})).revision,3);
assert.equal((await gate({action:'save',expectedRevision:3,body:pending})).result,'locked');
await assert.rejects(gate({action:'hold',expectedRevision:3,reason:''}),/Hold reason/);
assert.equal((await gate({action:'hold',expectedRevision:3,reason:'Receipt reversed; reconfirm deposit'})).revision,4);
assert.equal((await gate({action:'save',expectedRevision:4,body:pending})).revision,5);
assert.equal((await gate({action:'release',expectedRevision:5})).result,'incomplete');
const waived={...complete,depositStatus:'waived',depositAmount:'',currency:'',depositRef:'',depositOn:null,waiverReason:'Approved exception per accepted terms'};
await assert.rejects(gate({action:'save',expectedRevision:5,body:{...waived,waiverReason:''}}),/Invalid readiness/);
assert.equal((await gate({action:'save',expectedRevision:5,body:waived})).revision,6);
await db.exec("reset role;update project_inquiries set status='declined';set role authenticated;");
assert.equal((await gate({action:'release',expectedRevision:6})).result,'not_qualified');
await db.exec("reset role;update project_inquiries set status='qualified';set role authenticated;");
assert.equal((await gate({action:'release',expectedRevision:6})).revision,7);
const readiness=(await db.query('select * from inquiry_readiness')).rows[0];assert.equal(readiness.state,'ready');assert.equal(readiness.proposal_version,2);assert.equal(readiness.released_by,staff);
const history=(await db.query('select * from inquiry_readiness_history order by id')).rows;assert.equal(history.length,7);assert.equal(history[2].snapshot.body.depositRef,'RECEIPT-001');assert.equal(history[3].reason,'Receipt reversed; reconfirm deposit');
await db.exec('reset role;update inquiry_staff set active=false;set role authenticated;');assert.equal((await db.query('select * from inquiry_readiness_history')).rows.length,0);await assert.rejects(gate({action:'hold',expectedRevision:7,reason:'x'}),/Staff authorization/);
console.log('PASS: readiness migration, RLS/RPC authorization, evidence/date/amount validation, gate requirements, revision conflicts, locked ready records, hold/correction/release, waiver evidence, exact scope link and atomic snapshots');
await db.exec('reset role;update inquiry_staff set active=true;');
await db.exec(fs.readFileSync(new URL('202610060005_client_onboarding.sql',migrations),'utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${other}',false)`);
const onboard=async c=>(await db.query('select manage_inquiry_onboarding($1,$2) r',[id,c])).rows[0].r;
await assert.rejects(onboard({action:'start',expectedRevision:0}),/Staff authorization/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
assert.equal((await onboard({action:'start',expectedRevision:0})).revision,1);
assert.equal((await onboard({action:'start',expectedRevision:0})).result,'conflict');
assert.equal((await onboard({action:'complete',expectedRevision:1})).result,'incomplete');
await assert.rejects(db.query("update inquiry_onboarding set state='complete'"),/permission denied/);
const initial=(await db.query('select body from inquiry_onboarding')).rows[0].body;
await assert.rejects(onboard({action:'save',expectedRevision:1,body:{...initial,items:[]}}),/Invalid onboarding/);
const finished={...initial,contactName:'Contact',contactEmail:'contact@example.com',approver:'Approver',kickoffStatus:'held',kickoffDate:'2026-10-01',kickoffDetails:'10am America/Chicago; video; confirm scope',kickoffNotes:'Scope and responsibilities confirmed',items:initial.items.map(x=>({...x,status:'complete',notes:'Verified evidence ref'}))};
await assert.rejects(onboard({action:'save',expectedRevision:1,body:{...finished,kickoffDate:'2999-01-01'}}),/Invalid onboarding/);
await assert.rejects(onboard({action:'save',expectedRevision:1,body:{...finished,items:finished.items.map(x=>({...x,notes:''}))}}),/Invalid onboarding/);
assert.equal((await onboard({action:'save',expectedRevision:1,body:finished})).revision,2);
assert.equal((await onboard({action:'complete',expectedRevision:1})).result,'conflict');
assert.equal((await onboard({action:'complete',expectedRevision:2})).revision,3);
let ob=(await db.query('select * from inquiry_onboarding')).rows[0];assert.equal(ob.completed_readiness_revision,7);assert.equal(ob.completed_by,staff);assert.equal(ob.proposal_version,2);
assert.equal((await onboard({action:'save',expectedRevision:3,body:finished})).result,'locked');
assert.equal((await gate({action:'hold',expectedRevision:7,reason:'Agreement correction'})).revision,8);
await assert.rejects(onboard({action:'reopen',expectedRevision:3,reason:''}),/Reopen reason/);
assert.equal((await onboard({action:'reopen',expectedRevision:3,reason:'Gate changed; recheck inputs'})).revision,4);
assert.equal((await onboard({action:'complete',expectedRevision:4})).result,'gate_closed');
assert.equal((await onboard({action:'save',expectedRevision:4,body:finished})).revision,5);
assert.equal((await gate({action:'release',expectedRevision:8})).revision,9);
assert.equal((await onboard({action:'complete',expectedRevision:5})).revision,6);
ob=(await db.query('select * from inquiry_onboarding')).rows[0];assert.equal(ob.completed_readiness_revision,9);
assert.equal((await db.query('select * from inquiry_onboarding_history')).rows.length,6);
await db.exec('reset role;update inquiry_staff set active=false;set role authenticated;');assert.equal((await db.query('select * from inquiry_onboarding')).rows.length,0);assert.equal((await db.query('select * from inquiry_onboarding_history')).rows.length,0);
await assert.rejects(onboard({action:'reopen',expectedRevision:6,reason:'x'}),/Staff authorization/);
console.log('PASS: onboarding RLS, core checklist protection, required evidence, kickoff/date validation, completion gate, stale saves, hold/reopen/recompletion, readiness revision binding and history');
await db.exec('reset role;update inquiry_staff set active=true;');
await db.exec(fs.readFileSync(new URL('202610060006_project_workspace.sql',migrations),'utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${other}',false)`);
const project=async c=>(await db.query('select manage_inquiry_project($1,$2) r',[id,c])).rows[0].r;
await assert.rejects(project({action:'activate',expectedRevision:0}),/Staff authorization/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
await gate({action:'hold',expectedRevision:9,reason:'Recheck'});assert.equal((await project({action:'activate',expectedRevision:0})).result,'gate_closed');
await gate({action:'release',expectedRevision:10});assert.equal((await project({action:'activate',expectedRevision:0})).result,'gate_closed');
await onboard({action:'reopen',expectedRevision:6,reason:'New gate revision'});await onboard({action:'complete',expectedRevision:7});
assert.equal((await project({action:'activate',expectedRevision:0})).revision,1);assert.equal((await project({action:'activate',expectedRevision:0})).result,'conflict');
await assert.rejects(db.query("update inquiry_projects set state='completed'"),/permission denied/);
assert.equal((await project({action:'complete',expectedRevision:1,reason:'Done'})).result,'incomplete');
const work={title:'Brand launch',owner:'Designer',notes:'Internal plan',milestones:[{id:'m1',title:'Delivery',dueOn:'2026-10-20',status:'planned'}],tasks:[{id:'t1',title:'Produce files',owner:'Designer',dueOn:'2026-10-19',status:'todo',milestoneId:'m1',notes:''}]};
await assert.rejects(project({action:'save',expectedRevision:1,body:{...work,tasks:[{...work.tasks[0],milestoneId:'missing'}]}}),/Invalid project/);
await assert.rejects(project({action:'save',expectedRevision:1,body:{...work,milestones:[{...work.milestones[0],dueOn:'2026-02-30'}]}}),/Invalid project/);
assert.equal((await project({action:'save',expectedRevision:1,body:work})).revision,2);assert.equal((await project({action:'save',expectedRevision:1,body:work})).result,'conflict');
assert.equal((await project({action:'hold',expectedRevision:2,reason:'Client pause'})).revision,3);
await gate({action:'hold',expectedRevision:11,reason:'Recheck'});assert.equal((await project({action:'resume',expectedRevision:3,reason:'Resume'})).result,'gate_closed');
await gate({action:'release',expectedRevision:12});await onboard({action:'reopen',expectedRevision:8,reason:'New prerequisites'});await onboard({action:'complete',expectedRevision:9});
assert.equal((await project({action:'resume',expectedRevision:3,reason:'Verified'})).revision,4);
const finishedWork={...work,milestones:work.milestones.map(m=>({...m,status:'done'})),tasks:work.tasks.map(t=>({...t,status:'done'}))};
assert.equal((await project({action:'save',expectedRevision:4,body:finishedWork})).revision,5);assert.equal((await project({action:'complete',expectedRevision:5,reason:'Delivered'})).revision,6);
assert.equal((await project({action:'save',expectedRevision:6,body:work})).result,'locked');
assert.equal((await project({action:'reopen',expectedRevision:6,reason:'Review correction'})).revision,7);
const pr=(await db.query('select * from inquiry_projects')).rows[0];assert.equal(pr.state,'on_hold');assert.equal(pr.activated_readiness_revision,11);assert.equal(pr.activated_onboarding_revision,8);assert.equal(pr.scope_snapshot.title,'Second');assert.equal(pr.activated_by,staff);
assert.equal((await db.query('select * from inquiry_project_history')).rows.length,7);
await db.exec('reset role;update inquiry_staff set active=false;set role authenticated;');assert.equal((await db.query('select * from inquiry_projects')).rows.length,0);assert.equal((await db.query('select * from inquiry_project_history')).rows.length,0);await assert.rejects(project({action:'resume',expectedRevision:7,reason:'x'}),/Staff authorization/);
console.log('PASS: project activation requires current gates, duplicate/conflict handling, RLS, task/date/milestone validation, hold/resume/complete/reopen, frozen activation snapshots and history');
await db.exec('reset role;update inquiry_staff set active=true;');
await db.exec(fs.readFileSync(new URL('202610060007_client_portal.sql',migrations),'utf8'));
const observer='44444444-4444-4444-8444-444444444444',otherProject='55555555-5555-4555-8555-555555555555';
await db.exec(`insert into auth.users values('${observer}');insert into project_clients(request_id,user_id,can_review) values('${id}','${other}',true),('${id}','${observer}',false);`);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${other}',false)`);
const publish=async c=>(await db.query('select publish_project_update($1,$2) r',[id,c])).rows[0].r;
const clientReview=async c=>(await db.query('select review_project_publication($1,$2) r',[id,c])).rows[0].r;
await assert.rejects(publish({action:'publish',expectedVersion:0,body:{}}),/Staff authorization/);
assert.equal((await db.query('select * from inquiry_projects')).rows.length,0);
assert.equal((await db.query('select * from inquiry_onboarding')).rows.length,0);
await assert.rejects(db.query('select * from project_clients'),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
const pub={title:'Client update',summary:'Ready for review',nextSteps:'Review the draft files',progress:50,reviewRequested:true,milestones:[{title:'Direction',status:'done',dueOn:'2026-10-01'}],deliveries:[{id:'d1',label:'Files',url:'https://example.com/files',notes:'Version 1'}]};
await assert.rejects(publish({action:'publish',expectedVersion:0,body:{...pub,deliveries:[{...pub.deliveries[0],url:'javascript:alert(1)'}]}}),/Invalid publication/);
await assert.rejects(publish({action:'publish',expectedVersion:0,body:{...pub,internalNotes:'leak'}}),/Invalid publication/);
assert.equal((await publish({action:'publish',expectedVersion:0,body:pub})).version,1);
await db.exec('reset role;');
await db.query("insert into project_inquiries(request_id,payload,payload_hash,status) values($1,'{}',repeat('b',64),'qualified')",[otherProject]);
await db.query("insert into inquiry_proposals(request_id,version,body,status) select $1,1,body,'accepted' from inquiry_proposals where request_id=$2 and status='accepted'",[otherProject,id]);
await db.query("insert into inquiry_projects(request_id,proposal_version,revision,state,body,scope_snapshot,onboarding_snapshot,readiness_snapshot,activated_readiness_revision,activated_onboarding_revision) select $1,1,1,'active',body,scope_snapshot,onboarding_snapshot,readiness_snapshot,activated_readiness_revision,activated_onboarding_revision from inquiry_projects where request_id=$2",[otherProject,id]);
await db.query("insert into project_publications(request_id,version,body) values($1,1,$2)",[otherProject,{...pub,title:'Other client private update'}]);
await db.exec('set role authenticated;');

assert.equal((await publish({action:'publish',expectedVersion:0,body:pub})).result,'conflict');
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false)`);
assert.equal((await db.query('select request_id,version,body from project_publications')).rows.length,1);
assert.equal((await db.query('select * from client_project_latest')).rows.length,1);
await assert.rejects(db.query('select created_by from project_publications'),/permission denied/);
await assert.rejects(db.query("update project_publications set body='{}'"),/permission denied/);
await assert.rejects(clientReview({version:1,decision:'changes_requested',note:''}),/Invalid review/);
assert.equal((await clientReview({version:1,decision:'changes_requested',note:'Adjust contrast'})).result,'saved');
assert.equal((await clientReview({version:1,decision:'approved',note:''})).result,'conflict');
await db.exec(`select set_config('request.jwt.claim.sub','${observer}',false)`);
assert.equal((await db.query('select * from project_client_reviews')).rows.length,0);
await assert.rejects(clientReview({version:1,decision:'approved',note:''}),/reviewer authorization/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
assert.equal((await db.query('select * from project_client_reviews')).rows.length,1);
assert.equal((await publish({action:'publish',expectedVersion:1,body:{...pub,progress:100}})).version,2);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false)`);
assert.equal((await clientReview({version:1,decision:'approved',note:''})).result,'conflict');
assert.equal((await clientReview({version:2,decision:'approved',note:'Approved'})).result,'saved');
await assert.rejects(db.query('insert into project_client_reviews(request_id,version,user_id,decision,note) values($1,2,$2,$3,$4)',[id,observer,'approved','']),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${staff}',false)`);
await publish({action:'withdraw',expectedVersion:2,version:2});
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false)`);
assert.equal((await db.query('select request_id,version from project_publications')).rows.length,1);
assert.equal((await db.query('select * from client_project_latest')).rows[0].version,1);
await db.exec(`reset role;update project_clients set active=false where user_id='${other}';set role authenticated;`);
assert.equal((await db.query('select * from client_project_latest')).rows.length,0);
assert.equal((await db.query('select * from project_client_reviews')).rows.length,0);
await assert.rejects(clientReview({version:1,decision:'approved',note:''}),/reviewer authorization/);
await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from client_project_latest'),/permission denied/);
console.log('PASS: portal membership and viewer/approver isolation, no internal reads/writes, safe publication validation, immutable versions, stale and duplicate review rejection, client decisions, withdrawal and revocation');


await db.exec(`reset role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id bigint generated always as identity,bucket_id text,name text,metadata jsonb,unique(bucket_id,name));alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated,anon;grant usage on sequence storage.objects_id_seq to authenticated,anon;create policy old_broad on storage.objects for all to public using(true) with check(true);update project_clients set active=true;`);
await db.exec(fs.readFileSync(new URL('202610060008_project_files.sql',migrations),'utf8'));
const fid='66666666-6666-4666-8666-666666666666',clientFile='77777777-7777-4777-8777-777777777777';
const fileCmd=async c=>(await db.query('select manage_project_file($1,$2) r',[id,c])).rows[0].r;
const identity=async who=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${who}',false)`);
const reserve=(fileId,name='brief.pdf',size=3,mime='application/pdf')=>({action:'reserve',id:fileId,filename:name,size,mime});
await identity(staff);
assert.equal((await fileCmd(reserve(fid))).result,'reserved');assert.equal((await fileCmd(reserve(fid))).result,'reserved');
assert.equal((await fileCmd({...reserve(fid),filename:'other.pdf'})).result,'conflict');
await assert.rejects(fileCmd(reserve(randomUUID(),'../hack.pdf')),/Invalid file details/);
await assert.rejects(fileCmd(reserve(randomUUID(),'a\\b.pdf')),/Invalid file details/);
await assert.rejects(fileCmd(reserve(randomUUID(),'file.html',3,'text/html')),/Unsupported/);
await assert.rejects(fileCmd(reserve(randomUUID(),'big.pdf',10485761)),/Unsupported/);
assert.equal((await fileCmd({action:'finalize',id:fid})).result,'not_uploaded');
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['bivi-project-files',id+'/'+fid,{size:4,mimetype:'application/pdf'}]);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
assert.equal((await fileCmd({action:'finalize',id:fid})).result,'mismatch');
await db.exec(`reset role;update storage.objects set metadata='{"size":3,"mimetype":"application/pdf"}';`);await identity(staff);
assert.equal((await fileCmd({action:'finalize',id:fid})).result,'saved');assert.equal((await fileCmd({action:'finalize',id:fid})).result,'saved');
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
assert.equal((await db.query("update storage.objects set metadata='{}' returning *")).rows.length,0);
assert.equal((await db.query('delete from storage.objects returning *')).rows.length,0);
await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('bivi-project-files','unreserved')"),/row-level security/);
await identity(other);assert.equal((await db.query('select * from project_files')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
assert.equal((await fileCmd(reserve(clientFile,'client.txt',5,'text/plain'))).result,'reserved');
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['bivi-project-files',id+'/'+clientFile,{size:5,mimetype:'text/plain'}]);
assert.equal((await fileCmd({action:'finalize',id:clientFile})).result,'saved');
await assert.rejects(fileCmd({action:'share',id:clientFile,expectedRevision:1}),/Staff authorization/);
await assert.rejects(db.query('update project_files set shared=true'),/permission denied/);
assert.equal((await db.query('select * from project_file_history')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await identity(observer);assert.equal((await db.query('select * from project_files')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await assert.rejects(fileCmd({action:'finalize',id:clientFile}),/Uploader authorization/);
await identity(staff);assert.equal((await fileCmd({action:'share',id:fid,expectedRevision:1})).result,'saved');assert.equal((await fileCmd({action:'private',id:fid,expectedRevision:1})).result,'conflict');
await identity(observer);assert.equal((await db.query('select * from project_files')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await assert.rejects(db.query('select manage_project_file($1,$2)',[otherProject,reserve(randomUUID())]),/Project access/);
await identity(staff);await fileCmd({action:'private',id:fid,expectedRevision:2});await identity(observer);assert.equal((await db.query('select * from project_files')).rows.length,0);
await identity(staff);await assert.rejects(fileCmd({action:'withdraw',id:fid,expectedRevision:3,reason:''}),/Withdrawal reason/);await fileCmd({action:'withdraw',id:fid,expectedRevision:3,reason:'Replace outdated version'});
assert.equal((await fileCmd({action:'share',id:fid,expectedRevision:4})).result,'conflict');assert.equal((await db.query('select * from storage.objects')).rows.length,1);
assert.equal((await db.query('select * from project_file_history')).rows.length,7);
await identity(other);const expired=randomUUID();await fileCmd(reserve(expired));await db.exec(`reset role;update project_files set expires_at=now()-interval '1 second' where id='${expired}';`);await identity(other);
assert.equal((await fileCmd({action:'finalize',id:expired})).result,'conflict');await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['bivi-project-files',id+'/'+expired]),/row-level security/);
await db.exec(`reset role;update project_clients set active=false where user_id='${other}';`);await identity(other);assert.equal((await db.query('select * from project_files')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(fileCmd(reserve(randomUUID())),/Project access/);
await identity(staff);for(let i=0;i<19;i++)assert.equal((await fileCmd(reserve(randomUUID()))).result,'reserved');assert.equal((await fileCmd(reserve(randomUUID()))).result,'limit');
await db.exec(`reset role;insert into project_files(id,request_id,object_path,filename,size_bytes,mime_type) select md5('cap'||i)::uuid,'${otherProject}','${otherProject}/'||(md5('cap'||i)::uuid)::text,'cap.pdf',1,'application/pdf' from generate_series(1,200) i;`);await identity(staff);assert.equal((await db.query('select manage_project_file($1,$2) r',[otherProject,reserve(randomUUID())])).rows[0].r.result,'limit');
await db.exec(`reset role;set role anon;select set_config('request.jwt.claim.sub','',false);`);await assert.rejects(db.query('select * from project_files'),/permission denied/);await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('bivi-project-files','anonymous')"));
console.log('PASS: file migration, private bucket, retry-safe reservations, path/type/size validation, stored metadata verification, staff/client/project isolation, broad-policy guards, overwrite/delete denial, share/private/withdraw history, expiry, revocation and upload quotas');

await db.exec('reset role;');
await db.exec(fs.readFileSync(new URL('202610070009_project_discussion.sql',migrations),'utf8'));
const currentProject=(await db.query('select * from inquiry_projects where request_id=$1',[id])).rows[0];const savedTask=currentProject.body.tasks[0];
assert.ok(savedTask);
const commentId=randomUUID();const commentCmd=async c=>(await db.query('select manage_project_comment($1,$2) r',[id,c])).rows[0].r;
await identity(staff);
const createComment={action:'create',id:commentId,body:'Coordinate draft review',taskId:savedTask.id,expectedProjectRevision:currentProject.revision};
await assert.rejects(commentCmd({...createComment,body:'  '}),/Comment text/);
assert.equal((await commentCmd({...createComment,expectedProjectRevision:currentProject.revision-1})).result,'conflict');
assert.equal((await commentCmd({...createComment,id:randomUUID(),taskId:'missing-task'})).result,'task_missing');
assert.equal((await commentCmd(createComment)).result,'saved');assert.equal((await commentCmd(createComment)).result,'saved');
assert.equal((await db.query('select * from project_comment_history')).rows.length,1);
await assert.rejects(db.query("update project_comments set body='tampered'"),/permission denied/);
await identity(other);assert.equal((await db.query('select * from project_comments')).rows.length,0);assert.equal((await db.query('select * from project_comment_history')).rows.length,0);assert.equal((await db.query('select * from project_activity')).rows.length,0);
await assert.rejects(commentCmd({...createComment,id:randomUUID()}),/Staff authorization/);
await db.exec(`reset role;insert into inquiry_staff(user_id) values('${observer}');`);await identity(observer);
assert.equal((await db.query('select * from project_comments')).rows.length,1);
await assert.rejects(commentCmd({action:'edit',id:commentId,body:'Unauthorized edit',expectedRevision:1}),/author authorization/);
await assert.rejects(commentCmd({action:'remove',id:commentId,expectedRevision:1}),/author authorization/);
await identity(staff);
assert.equal((await commentCmd({action:'edit',id:commentId,body:'Updated review notes',expectedRevision:1})).result,'saved');
assert.equal((await commentCmd({action:'edit',id:commentId,body:'Stale text',expectedRevision:1})).result,'conflict');
assert.equal((await commentCmd({action:'edit',id:commentId,body:'Updated review notes',expectedRevision:2})).result,'saved');
assert.equal((await db.query('select * from project_comment_history')).rows.length,2);
const changedProject={...currentProject.body,tasks:[]};assert.equal((await project({action:'save',expectedRevision:currentProject.revision,body:changedProject})).result,'saved');
assert.equal((await commentCmd({...createComment,id:randomUUID()})).result,'conflict');
assert.equal((await commentCmd({...createComment,id:randomUUID(),expectedProjectRevision:currentProject.revision+1})).result,'task_missing');
assert.equal((await commentCmd({action:'edit',id:commentId,body:'Task removed; keep context',expectedRevision:2})).result,'saved');
const preserved=(await db.query('select * from project_comments')).rows[0];assert.equal(preserved.task_title,savedTask.title);
assert.equal((await commentCmd({action:'remove',id:commentId,expectedRevision:3})).result,'saved');
assert.equal((await commentCmd({action:'edit',id:commentId,body:'Restore forbidden',expectedRevision:4})).result,'conflict');
const removed=(await db.query('select * from project_comments')).rows[0];assert.equal(removed.body,'');assert.equal(removed.removed,true);
const snapshots=(await db.query('select * from project_comment_history order by id')).rows;assert.equal(snapshots.length,4);assert.equal(snapshots[0].snapshot.body,'Coordinate draft review');
const feed=(await db.query('select * from project_activity where request_id=$1',[id])).rows;assert.ok(feed.some(e=>e.source==='comment'&&e.action==='remove'));assert.ok(feed.some(e=>e.source==='publication'&&e.action==='withdraw'));assert.ok(feed.some(e=>e.source==='file'));assert.ok(feed.every(e=>e.request_id===id));
const whole={action:'create',id:randomUUID(),body:'Project handoff note',taskId:null,expectedProjectRevision:currentProject.revision+1};assert.equal((await commentCmd(whole)).result,'saved');
await db.exec(`reset role;insert into project_comments(id,request_id,body) select md5('comment-cap'||i)::uuid,'${id}','Capacity fixture' from generate_series(1,998) i;`);await identity(staff);assert.equal((await commentCmd({...whole,id:randomUUID()})).result,'limit');
await db.exec(`reset role;update inquiry_staff set active=false where user_id='${staff}';`);await identity(staff);assert.equal((await db.query('select * from project_activity')).rows.length,0);await assert.rejects(commentCmd({...whole,id:randomUUID()}),/Staff authorization/);
await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from project_activity'),/permission denied/);await assert.rejects(db.query('select * from project_comments'),/permission denied/);
console.log('PASS: staff discussion migration, author-only editing/removal, client/anonymous/revoked-staff isolation, idempotency, stale project/comment revisions, removed-task context, soft removal history and unified activity');

} finally { await db.close(); }
});
