'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {emptyReadiness,readinessBodySchema,readinessChecks,type ReadinessBody} from '@/lib/onboarding/schema';
import type {ReadinessEvent,ReadinessRecord} from '@/lib/onboarding/data';
const dateLabel=(value:string)=>new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value))+' UTC';
export function OnboardingReadiness({id,version,qualified,record,history}:{id:string;version:number;qualified:boolean;record:ReadinessRecord|null;history:ReadinessEvent[]}){
 const router=useRouter();const [body,setBody]=useState<ReadinessBody>(record?.body??emptyReadiness);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [blocked,setBlocked]=useState(false);const [message,setMessage]=useState('');
 const ready=record?.state==='ready';const dirty=JSON.stringify(body)!==JSON.stringify(record?.body??emptyReadiness);const checks=readinessChecks(record?.body??emptyReadiness);
 function change<K extends keyof ReadinessBody>(key:K,value:ReadinessBody[K]){setBody(prev=>({...prev,[key]:value}));}
 async function command(action:'save'|'release'|'hold'){
  if(action==='save'&&!readinessBodySchema.safeParse(body).success){setMessage('Check the record fields, amount, currency and dates.');return;}
  if(action!=='save'&&!window.confirm(action==='release'?'Mark accepted scope version '+version+' ready for onboarding using the saved agreement and deposit records?':'Place onboarding readiness on hold? Further onboarding should wait until the gate is released again.'))return;
  setBusy(true);setMessage('');
  try{
   const r=await fetch(`/api/admin/leads/${id}/readiness`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,expectedRevision:record?.revision??0,...(action==='save'?{body}:action==='hold'?{reason}:{})}),signal:AbortSignal.timeout(20000)});const data=await r.json();
   if(r.status===401){router.replace('/admin/login');router.refresh();return;}
   if(r.status===409)setBlocked(true);if(!r.ok)throw new Error(data.error||'The record could not be saved.');window.location.reload();
  }catch(err){setMessage(err instanceof Error&&err.name!=='TimeoutError'?err.message:'The result could not be confirmed. Reload before retrying.');if(err instanceof Error&&(err.name==='TimeoutError'||err.name==='TypeError'))setBlocked(true);}
  finally{setBusy(false);}
 }
 const input=(key:'agreementRef'|'signatory'|'depositAmount'|'currency'|'depositRef',label:string,max:number)=><div><label htmlFor={`gate-${key}`} className="mb-2 block text-sm font-medium">{label}</label><Input id={`gate-${key}`} value={body[key]} maxLength={max} onChange={e=>change(key,key==='currency'?e.target.value.toUpperCase():e.target.value)} /></div>;
 const date=(key:'signedOn'|'depositOn',label:string)=><div><label htmlFor={`gate-${key}`} className="mb-2 block text-sm font-medium">{label}</label><Input id={`gate-${key}`} type="date" value={body[key]??''} onChange={e=>change(key,e.target.value||null)}/></div>;
 return <div className="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
  <div className="min-w-0 space-y-6"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Agreement and deposit records</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Record the agreement and deposit verified through your existing process. References stay internal. This screen records evidence; it does not sign documents or process payments.</p>
   <fieldset disabled={busy||blocked||ready} className="mt-6 space-y-5"><legend className="sr-only">Agreement and deposit evidence</legend>
    <div><label htmlFor="gate-agreement" className="mb-2 block text-sm font-medium">Agreement status</label><select id="gate-agreement" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm" value={body.agreementStatus} onChange={e=>change('agreementStatus',e.target.value as ReadinessBody['agreementStatus'])}><option value="pending">Pending</option><option value="signed">Signed</option></select></div>
    {input('agreementRef','Agreement reference or document location',2000)}{input('signatory','Client signatory',200)}{date('signedOn','Signed date')}
    <div className="border-t border-border pt-5"><label htmlFor="gate-deposit" className="mb-2 block text-sm font-medium">Deposit status</label><select id="gate-deposit" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm" value={body.depositStatus} onChange={e=>change('depositStatus',e.target.value as ReadinessBody['depositStatus'])}><option value="pending">Pending</option><option value="received">Received</option><option value="waived">Waived by staff</option></select></div>
    {body.depositStatus!=='waived'&&<>{input('depositAmount','Amount received',12)}{input('currency','Currency code (for example USD)',3)}{input('depositRef','Receipt or transaction reference',2000)}{date('depositOn','Received date')}</>}
    {body.depositStatus==='waived'&&<div><label htmlFor="gate-waiver" className="mb-2 block text-sm font-medium">Deposit waiver reason</label><Textarea id="gate-waiver" maxLength={2000} rows={3} value={body.waiverReason} onChange={e=>change('waiverReason',e.target.value)}/><p className="mt-2 text-xs text-muted-foreground">Use only when authorized under your agreed commercial terms. The staff actor and reason are retained in history.</p></div>}
    <div><label htmlFor="gate-notes" className="mb-2 block text-sm font-medium">Internal notes</label><Textarea id="gate-notes" maxLength={4000} rows={4} value={body.notes} onChange={e=>change('notes',e.target.value)}/></div>
    <Button type="button" onClick={()=>command('save')}>{busy?'Saving…':'Save records'}</Button>
   </fieldset>{ready&&<p className="mt-4 text-sm text-muted-foreground">Place readiness on hold before correcting these records.</p>}
  </section>
  <section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Readiness history</h2><p className="mt-2 text-xs text-muted-foreground">Latest 50 events with saved evidence snapshots.</p><ol className="mt-5 space-y-5">{history.map(event=><li key={event.id} className="border-l-2 border-border pl-4"><p className="text-sm font-medium">{event.action==='save'?'Records saved':event.action==='release'?'Ready for onboarding':'Placed on hold'} · version {event.snapshot.proposalVersion}</p><p className="mt-1 text-xs text-muted-foreground">{dateLabel(event.created_at)}</p>{event.reason&&<p className="mt-2 whitespace-pre-wrap break-words text-sm">{event.reason}</p>}<p className="mt-2 break-all font-mono text-[10px] text-muted-foreground">Staff: {event.actor||'Account removed'}</p><details className="mt-3 text-sm"><summary className="cursor-pointer underline underline-offset-4">View saved evidence</summary><dl className="mt-3 space-y-3">{Object.entries(event.snapshot.body).map(([key,value])=><div key={key}><dt className="text-xs text-muted-foreground">{({agreementStatus:'Agreement status',agreementRef:'Agreement reference',signatory:'Client signatory',signedOn:'Signed date',depositStatus:'Deposit status',depositAmount:'Amount received',currency:'Currency',depositRef:'Deposit reference',depositOn:'Received date',waiverReason:'Waiver reason',notes:'Internal notes'} as Record<string,string>)[key]}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{value||'Not recorded'}</dd></div>)}</dl></details></li>)}</ol>{!history.length&&<p className="mt-5 text-sm text-muted-foreground">No readiness changes yet.</p>}</section></div>
  <aside className="space-y-5 lg:sticky lg:top-8"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Onboarding gate</h2><p className="mt-3 text-sm font-medium">{ready?(qualified?'Ready for onboarding':'Release recorded; inquiry no longer qualified'):'Pending / on hold'}</p><ul className="mt-5 space-y-3 text-sm"><li>Accepted scope: version {version}</li><li>Inquiry qualification: {qualified?'Qualified':'Not qualified'}</li><li>Signed agreement: {checks.agreement?'Recorded':'Missing'}</li><li>Deposit: {checks.deposit?'Received or explicitly waived':'Pending'}</li></ul>
   {!ready?<><Button type="button" className="mt-6 w-full" disabled={busy||blocked||dirty||!qualified||!record||!checks.agreement||!checks.deposit} onClick={()=>command('release')}>Release for onboarding</Button>{dirty&&<p className="mt-3 text-xs text-muted-foreground">Save changes before releasing.</p>}{!qualified&&<p className="mt-3 text-xs text-muted-foreground">The inquiry must be qualified.</p>}</>:<fieldset disabled={busy||blocked} className="mt-5 space-y-3"><legend className="sr-only">Place readiness on hold</legend><label htmlFor="gate-hold" className="block text-sm">Reason to place on hold</label><Textarea id="gate-hold" value={reason} maxLength={2000} rows={3} onChange={e=>setReason(e.target.value)}/><Button type="button" variant="outline" className="w-full" disabled={!reason.trim()} onClick={()=>command('hold')}>Place on hold</Button></fieldset>}
   {record?.released_at&&<p className="mt-4 text-xs text-muted-foreground">Released {dateLabel(record.released_at)}</p>}<p className="mt-5 text-xs leading-relaxed text-muted-foreground">This records readiness. Client onboarding checklists and project activation follow in the next batch.</p>
  </section>{message&&<p role="status" className="text-sm">{message}</p>}{blocked&&<Button type="button" variant="outline" onClick={()=>window.location.reload()}>Reload readiness</Button>}</aside>
 </div>;
}
