'use client';
import {useRef,useState} from 'react';import {useRouter} from 'next/navigation';import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import type {ProjectComment} from '@/lib/discussion/data';import type {ProjectBody} from '@/lib/projects/schema';
export function ProjectDiscussion({id,revision,tasks,comments,userId,filteredTask}:{id:string;revision:number;tasks:ProjectBody['tasks'];comments:ProjectComment[];userId:string;filteredTask:string|null}){
 const router=useRouter();const [body,setBody]=useState('');const [task,setTask]=useState(tasks.some(t=>t.id===filteredTask)?filteredTask!:'');const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [blocked,setBlocked]=useState(false);const pending=useRef<{id:string;body:string;taskId:string|null;expectedProjectRevision:number}|null>(null);
 async function command(action:'create'|'edit'|'remove',comment?:ProjectComment){
  if(action==='remove'&&!window.confirm('Remove your comment from the discussion? Staff audit history is retained.'))return;
  if(action==='create'){if(!body.trim()){setMessage('Enter a comment.');return;}if(!pending.current||pending.current.body!==body.trim()||pending.current.taskId!==(task||null))pending.current={id:crypto.randomUUID(),body:body.trim(),taskId:task||null,expectedProjectRevision:revision};}
  setBusy(true);setMessage('');
  try{const response=await fetch(`/api/admin/projects/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='create'?{action,...pending.current}:{action,id:comment!.id,expectedRevision:comment!.revision,...(action==='edit'?{body:draft}:{})}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(response.status===401){router.replace('/admin/login');router.refresh();return;}if(response.status===409)setBlocked(true);if(!response.ok)throw new Error(data.error||'Comment could not be saved.');pending.current=null;setBody('');setEditing(null);setMessage(action==='remove'?'Comment removed.':'Comment saved.');router.refresh();}catch(error){setMessage(error instanceof Error&&error.name!=='TimeoutError'?error.message:'The result could not be confirmed. Reload to check whether the comment was saved.');}finally{setBusy(false);}
 }
 return <section className="mt-8 space-y-5" aria-label="Project discussion"><div className="rounded-2xl border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Add a staff comment</h2><p className="mt-3 text-sm text-muted-foreground">Comments are internal. Choose a saved task or discuss the whole project.</p><fieldset disabled={busy||blocked} className="mt-5 space-y-4"><legend className="sr-only">Comment composer</legend><div><label htmlFor="comment-task" className="mb-2 block text-sm">Comment subject</label><select id="comment-task" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm" value={task} onChange={e=>setTask(e.target.value)}><option value="">Whole project</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></div><div><label htmlFor="comment-body" className="mb-2 block text-sm">Comment</label><Textarea id="comment-body" value={body} maxLength={4000} rows={4} onChange={e=>setBody(e.target.value)}/></div><Button type="button" disabled={!body.trim()} onClick={()=>command('create')}>Post comment</Button></fieldset>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}{blocked&&<Button type="button" variant="outline" className="mt-3" onClick={()=>window.location.reload()}>Reload discussion</Button>}</div>
 {!comments.length&&<p className="text-sm text-muted-foreground">No comments in this view yet.</p>}{comments.map(c=><article key={c.id} className="rounded-2xl border border-border bg-card p-5"><h3 className="break-words font-medium">{c.task_id?c.task_title:'Whole project'}{c.task_id&&!tasks.some(t=>t.id===c.task_id)&&<span className="ml-2 text-xs text-muted-foreground">Task removed</span>}</h3><p className="mt-2 text-xs text-muted-foreground">{c.author_id===userId?'You':'Staff'} · {new Date(c.created_at).toISOString().slice(0,16).replace('T',' ')} UTC{c.revision>1?' · Updated':''}</p>{c.removed?<p className="mt-4 text-sm text-muted-foreground">Comment removed. Audit history retained.</p>:editing===c.id?<div className="mt-4 space-y-3"><label htmlFor={`edit-${c.id}`} className="block text-sm">Edit comment</label><Textarea id={`edit-${c.id}`} value={draft} maxLength={4000} onChange={e=>setDraft(e.target.value)} disabled={busy||blocked}/><div className="flex flex-wrap gap-3"><Button type="button" disabled={busy||blocked||!draft.trim()} onClick={()=>command('edit',c)}>Save comment</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditing(null)}>Cancel edit</Button></div></div>:<p className="mt-4 whitespace-pre-wrap break-words text-sm">{c.body}</p>}{!c.removed&&c.author_id===userId&&editing!==c.id&&<div className="mt-4 flex flex-wrap gap-3"><Button type="button" variant="outline" disabled={busy||blocked} onClick={()=>{setEditing(c.id);setDraft(c.body);}}>Edit comment</Button><Button type="button" variant="outline" disabled={busy||blocked} onClick={()=>command('remove',c)}>Remove comment</Button></div>}</article>)}
 </section>;
}
