'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
type Member={user_id:string;active:boolean;can_review:boolean;revision:number};
export function ProjectAccess({id,members}:{id:string;members:Member[]}){
 const router=useRouter();const [email,setEmail]=useState(''),[userId,setUserId]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[link,setLink]=useState('');
 async function save(command:object){setBusy(true);setMessage('');setLink('');try{const response=await fetch(`/api/admin/projects/${id}/access`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(25000)});const data=await response.json();if(response.status===401){router.replace('/admin/login');return;}if(!response.ok){if(response.status===409||response.status>=500)setBlocked(true);throw new Error((data.error||'Access could not be saved.')+(data.userId?` Auth account ID: ${data.userId}`:''));}setLink(data.link||'');setMessage(data.link?'Invitation prepared. Share this private link with the intended client. No email was sent.':'Access saved.');setUserId('');setEmail('');router.refresh();}catch(error){setBlocked(true);setMessage(error instanceof Error&&error.name!=='TimeoutError'?error.message:'Result uncertain. Reload and check Auth before retrying.');}finally{setBusy(false);}}
 return <div className="mt-8 space-y-6"><fieldset disabled={busy||blocked} className="rounded-2xl border border-border bg-card p-6"><legend className="px-2 text-xl font-semibold">Prepare a client invitation</legend><p className="mb-4 text-sm text-muted-foreground">For a new account. Confirm the recipient and share the generated link through your existing channel.</p><label htmlFor="invite-email" className="block text-sm">Client email</label><Input id="invite-email" type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} className="mt-2"/><label className="my-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/>Allow delivery approval and change requests</label><Button type="button" disabled={!email.trim()} onClick={()=>save({action:'invite',email,canReview:review})}>Prepare invitation</Button></fieldset>
 <fieldset disabled={busy||blocked} className="rounded-2xl border border-border bg-card p-6"><legend className="px-2 text-xl font-semibold">Assign an existing account</legend><label htmlFor="account-id" className="block text-sm">Auth account ID</label><Input id="account-id" value={userId} onChange={e=>setUserId(e.target.value)} className="my-3"/><p className="mb-4 text-sm text-muted-foreground">Copy the UUID from Supabase Auth. New assignments start as viewers.</p><Button type="button" disabled={!userId.trim()} onClick={()=>save({action:'assign',userId:userId.trim(),expectedRevision:0,active:true,canReview:false})}>Assign viewer</Button></fieldset>
 {message&&<p role="status" className="break-words text-sm">{message}</p>}{blocked&&<Button variant="outline" onClick={()=>window.location.reload()}>Reload access</Button>}{link&&<div className="rounded-xl border border-border p-5"><label htmlFor="invitation-link" className="block text-sm">Private invitation link</label><Input id="invitation-link" readOnly value={link} className="my-3"/><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Link copied. Share only with the intended client.');}catch{setMessage('Select the link and copy it manually.');}}}>Copy link</Button><p className="mt-3 text-sm text-muted-foreground">This link grants account setup. It disappears when this page reloads.</p></div>}
 <section><h2 className="text-xl font-semibold">Assigned accounts</h2><p className="mt-3 text-sm text-muted-foreground">Latest 100 assignments. Revoking access removes project access; it does not delete the account.</p>{members.map(m=><article key={m.user_id} className="mt-4 rounded-xl border border-border p-5"><p className="break-all text-sm">{m.user_id}</p><p className="my-3 text-sm">{m.active?'Active':'Revoked'} · {m.can_review?'Reviewer':'Viewer'}</p><div className="flex flex-wrap gap-3"><Button variant="outline" disabled={busy||blocked} onClick={()=>save({action:'assign',userId:m.user_id,expectedRevision:m.revision,active:!m.active,canReview:m.can_review})}>{m.active?'Revoke access':'Restore access'}</Button><Button variant="outline" disabled={busy||blocked} onClick={()=>save({action:'assign',userId:m.user_id,expectedRevision:m.revision,active:m.active,canReview:!m.can_review})}>{m.can_review?'Make viewer':'Allow reviews'}</Button></div></article>)}</section></div>;
}
